---
# yamllint disable rule:line-length
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # v1.5.6
    hooks:
      - id: forbid-tabs
        exclude_types: [python, javascript, dtd, markdown, makefile, xml]
        exclude: binary|\.bin$
  - repo: https://github.com/jameswoolfenden/pre-commit-shell
    rev: 062f0b028ae65827e04f91c1e6738cfcbe9b337f # v1.0.6
    hooks:
      - id: shell-lint
        exclude: template|\.template$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e # v0.48.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/jameswoolfenden/pre-commit
    rev: 4997cf8b63896568143d5c6e820741214bc9f314 # v0.1.61
    hooks:
      - id: terraform-fmt
      - id: tf2docs
  - repo: https://github.com/bridgecrewio/checkov
    rev: e77b5f7422ad23034c1a3c0a1902cd7e9eb60caf # 3.2.527
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d example/examplea --external-checks-dir checkov --download-external-modules true --compact
  - repo: https://github.com/jameswoolfenden/pike
    rev: 26feee4bf690195c46456bce70ad8b292fac8a35 # v0.4.4
    hooks:
      - id: pike-docs-go
        args: ["readme", "-d", ".", "-i"]
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/jameswoolfenden/ghat
    rev: e60f56cec93d64866fa82cf6511ce7c0cd92bb20 # v0.1.29
    hooks:
      - id: ghat-go
      - id: ghat-go-sift
