module "codebuild" {
  source                 = "github.com/jameswoolfenden/terraform-aws-codebuild"
  bucketname             = "${var.bucketname}"
  build_timeout          = "${var.build_timeout}"
  common_tags            = "${var.common_tags}"
  description            = "${var.description}"
  env                    = "${var.env}"
  environment            = "${var.environment}"
  force_artifact_destroy = "${var.force_artifact_destroy}"
  name                   = "${var.name}"
  projectroot            = "${var.projectroot}"
  reponame               = "${var.name}"
  sourcecode             = "${var.sourcecode}"
  type                   = "${var.type}"
  encryption_disabled    = "${var.encryption_disabled}"
}
