module "codepipeline" {
  source = "../../"
  artifact_store         = "${var.artifact_store}"
  bucketname             = "${lookup(var.artifact_store[0],"location")}"
  build_timeout          = "${var.build_timeout}"
  common_tags            = "${var.common_tags}"
  description            = "${var.description}"
  env                    = "${var.env}"
  environment            = "${var.environment}"
  force_artifact_destroy = "${var.force_artifact_destroy}"
  name                   = "${var.name}"
  projectroot            = "${var.projectroot}"
  sourcecode             = "${var.sourcecode}"
  stage                  = "${var.stage}"
  type                   = "${var.type}"
}
